"use strict";

/**
 * Exports a chapter → lecture index as Markdown and/or HTML inside the course folder.
 */

const fs = require("fs");
const path = require("path");
const sanitize = require("sanitize-filename");

/**
 * @param {string} text
 * @returns {string}
 */
function escapeHtml(text) {
	return String(text || "")
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

/**
 * @param {object} courseData
 * @returns {{ chapters: Array<{ name: string, lectures: Array<{ name: string, type: string, duration?: string, encrypted?: boolean }> }> , name: string }}
 */
function normalizeStructure(courseData) {
	const name = String(courseData?.name || courseData?.title || "Course").trim() || "Course";
	const chapters = (courseData?.chapters || []).map((chapter) => ({
		name: String(chapter?.name || "Chapter").trim() || "Chapter",
		lectures: (chapter?.lectures || []).map((lecture) => ({
			name: String(lecture?.name || "Lecture").trim() || "Lecture",
			type: String(lecture?.type || lecture?.quality || "video"),
			duration: lecture?.duration ? String(lecture.duration) : "",
			encrypted: Boolean(lecture?.isEncrypted),
		})),
	}));
	return { name, chapters };
}

/**
 * @param {{ name: string, chapters: object[] }} structure
 * @returns {string}
 */
function toMarkdown(structure) {
	const lines = [`# ${structure.name}`, "", `> Generated by CursoDown`, ""];
	structure.chapters.forEach((chapter, ci) => {
		lines.push(`## ${ci + 1}. ${chapter.name}`, "");
		chapter.lectures.forEach((lecture, li) => {
			const meta = [];
			if (lecture.duration) meta.push(lecture.duration);
			if (lecture.encrypted) meta.push("DRM");
			else if (lecture.type) meta.push(lecture.type);
			const suffix = meta.length ? ` _( ${meta.join(" · ")} )_` : "";
			lines.push(`${li + 1}. ${lecture.name}${suffix}`);
		});
		lines.push("");
	});
	return lines.join("\n");
}

/**
 * @param {{ name: string, chapters: object[] }} structure
 * @returns {string}
 */
function toHtml(structure) {
	const sections = structure.chapters
		.map((chapter, ci) => {
			const items = chapter.lectures
				.map((lecture, li) => {
					const badges = [];
					if (lecture.duration) badges.push(`<span class="meta">${escapeHtml(lecture.duration)}</span>`);
					if (lecture.encrypted) badges.push(`<span class="drm">DRM</span>`);
					else if (lecture.type) badges.push(`<span class="meta">${escapeHtml(lecture.type)}</span>`);
					return `<li><span class="n">${li + 1}.</span> ${escapeHtml(lecture.name)} ${badges.join(" ")}</li>`;
				})
				.join("\n");
			return `<section>
  <h2>${ci + 1}. ${escapeHtml(chapter.name)}</h2>
  <ol>${items || "<li><em>Empty</em></li>"}</ol>
</section>`;
		})
		.join("\n");

	return `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(structure.name)}</title>
  <style>
    :root { color-scheme: light dark; }
    body { font-family: system-ui, Segoe UI, sans-serif; margin: 0; padding: 2rem; line-height: 1.5; max-width: 52rem; }
    h1 { margin-top: 0; }
    h2 { margin-top: 1.75rem; border-bottom: 1px solid #8884; padding-bottom: .35rem; }
    ol { padding-left: 1.25rem; }
    li { margin: .35rem 0; }
    .meta { opacity: .65; font-size: .85em; margin-left: .35rem; }
    .drm { color: #e11; font-size: .75em; font-weight: 700; margin-left: .35rem; }
    .n { opacity: .5; margin-right: .25rem; }
    footer { margin-top: 2rem; opacity: .55; font-size: .85rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(structure.name)}</h1>
  <p>Índice del curso · CursoDown</p>
  ${sections}
  <footer>Generated by CursoDown</footer>
</body>
</html>
`;
}

/**
 * Writes INDEX.md and/or index.html into the course folder.
 * @param {object} courseData
 * @param {string} coursePath
 * @param {{ markdown?: boolean, html?: boolean }} [options]
 * @returns {{ dir: string, files: string[] }}
 */
function exportCourseIndex(courseData, coursePath, options = {}) {
	if (!coursePath) {
		throw new Error("Course path is required");
	}
	const writeMd = options.markdown !== false;
	const writeHtml = options.html !== false;
	const structure = normalizeStructure(courseData);
	fs.mkdirSync(coursePath, { recursive: true });

	const files = [];
	if (writeMd) {
		const mdPath = path.join(coursePath, "INDEX.md");
		fs.writeFileSync(mdPath, toMarkdown(structure), "utf8");
		files.push(mdPath);
	}
	if (writeHtml) {
		const htmlPath = path.join(coursePath, "index.html");
		fs.writeFileSync(htmlPath, toHtml(structure), "utf8");
		files.push(htmlPath);
	}

	return { dir: coursePath, files, name: structure.name };
}

/**
 * Builds a lightweight structure object from an on-disk chapter tree (fallback).
 * @param {string} coursePath
 * @param {string} [courseName]
 */
function structureFromFolder(coursePath, courseName) {
	const name = courseName || sanitize(path.basename(coursePath)) || "Course";
	if (!coursePath || !fs.existsSync(coursePath)) {
		return { name, chapters: [] };
	}
	const chapters = fs
		.readdirSync(coursePath, { withFileTypes: true })
		.filter((d) => d.isDirectory() && d.name !== "subs")
		.sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }))
		.map((dirent) => {
			const chapterPath = path.join(coursePath, dirent.name);
			const lectures = fs
				.readdirSync(chapterPath, { withFileTypes: true })
				.filter((f) => f.isFile())
				.map((f) => ({
					name: f.name.replace(/\.[^.]+$/, ""),
					type: path.extname(f.name).slice(1) || "file",
					duration: "",
					encrypted: false,
				}));
			return { name: dirent.name, lectures };
		});
	return { name, chapters };
}

module.exports = {
	exportCourseIndex,
	structureFromFolder,
	toMarkdown,
	toHtml,
	normalizeStructure,
};
